name: Publish Docker image

on:
  # push:
  pull_request:
    branches: [ main ]

jobs:
  docker-image-build:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v18
    - id: restore-nix-store
      name: Restore cached Nix store
      uses: actions/cache/restore@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-store
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: nix build -L .#dockerIntegrationTest
    - id: save-nix-store
      name: Cache Nix store
      uses: actions/cache/save@v3
      with:
        path: /nix/store
        key: ${{ steps.restore-nix-store.outputs.cache-primary-key }}
    - name: Load Docker image
      run: docker load < result
    - name: Tag Docker image
      run: docker tag obce-docker-image:latest ghcr.io/727-ventures/obce-docker-image:latest
    - name: Push Docker image
      run: docker push ghcr.io/727-ventures/obce-docker-image:latest
